name: Simple Workflow with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: 'Hello'
      CAPITALIZE: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Greeting
        run: |
          if [ "${{ env.CAPITALIZE }}" == "true" ]; then
            echo "${{ env.GREETING }}" | awk '{print toupper($0)}'
          else
            echo "${{ env.GREETING }}"
          fi
